FROM node:latest

WORKDIR /usr/app
# RUN chown -R node:node /home/node/app

# COPY --chown=node:node package.json .

COPY . .

RUN npm i --force

# COPY --chown=node:node . .

# USER node

EXPOSE 3000

CMD ["npm", "run", "start:watch"]