FROM node:latest

WORKDIR /home/node/app
RUN chown -R node:node /home/node/app

COPY --chown=node:node package.json .

RUN npm i

COPY --chown=node:node . .

USER node

EXPOSE 8080

CMD ["npm", "run", "dev"]