FROM node:latest

WORKDIR /usr/app
# RUN chown -R node:node /home/node/app

# COPY --chown=node:node package.json .

COPY . .

RUN npm i

# COPY --chown=node:node . .

# USER node

EXPOSE 8080

CMD ["npm", "run", "dev"]